# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
<<<<<<< HEAD
  secret_key_base: 6fc9f446a719f7909fa13b15541aaf00940da041f945e04fc3d6fc069078798d11c2f9a01e1f74a9621adb8c273f669c24074203b7b28c1746880c82e4ba75bd

test:
  secret_key_base: f37c73987e74d93db6665596203600cdad6ed1d6ef547ce911f2cc3f89713aab51040a6dc5f1d5b570f8d3aad4b0ca9514e0c23af9d9ef021e4d464a0a366889
=======
  secret_key_base: 8428b1d79128a9d326eeee0d833993aa84cff284c52558d3999514485f2da77531aa1aa50795273e2ac5211af249962abb7ec65ecbefcbcf73035470d03b6ce8

test:
  secret_key_base: 344042e482b998f07d20096a8e8a6458a3d69488b9ba74283061db61faaaa22e46a94281313bc49703d71d20d0944598a458c51e379c7f65ccdc791999768b63
>>>>>>> e6fd0af14712eb47d06304fa62c527708947d6cd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
